### ISSUE TITLE
Really great, need help for JAVA 8 features

### ISSUE THREAD

**Issue by DroidPulkit** [kawnayeen/AndroidUtil#1]
Hey, Really great library
But don't the JAVA 8 features like lambda expressions cause some errors?
BTW as a side note my AS don't support java 8 features, can you let me know how to achieve it.
Thank You

**Comment by DroidPulkit** [comment]
Also @kawnayeen is there any known issue?

**Comment by kawnayeen** [comment]
1) only the example project is using java 8 features, not the library that's you are going to import.
2) lambda expressions doesn't cause any problem. besides latest android build tool (although in beta ) has built in support for java 8, we don't need to use jack there. 
3) don't have any known issue yet.

**Comment by DroidPulkit** [comment]
Thanks for the info, surely the example will work in AS 3.0 beta 5 :+1:
